# Generated by Django 5.1.4 on 2025-11-22 22:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FloodSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(help_text='Short station handle or ID used in URLs.', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Display name for the site.', max_length=255)),
                ('location_description', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('active', models.BooleanField(default=True)),
                ('imei', models.CharField(blank=True, help_text='Optional IMEI or device identifier used in payloads.', max_length=32)),
                ('trigger_low_low_mm', models.IntegerField(blank=True, help_text='Distance (mm) at or below which bed is considered dry.', null=True)),
                ('trigger_low_mm', models.IntegerField(blank=True, help_text='Distance (mm) above dry bed where water is first detected.', null=True)),
                ('trigger_high_mm', models.IntegerField(blank=True, help_text='Distance (mm) where water over road is likely.', null=True)),
                ('trigger_high_high_mm', models.IntegerField(blank=True, help_text='Distance (mm) where water over road is significant.', null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flood_sites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['handle'],
            },
        ),
        migrations.CreateModel(
            name='Uplink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_mm', models.IntegerField(help_text='Measured distance in mm.')),
                ('battery_v', models.FloatField(blank=True, null=True)),
                ('signal_dbm', models.IntegerField(blank=True, null=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uplinks', to='flood.floodsite')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
