# Generated by Django 5.1.4 on 2025-11-22 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(max_length=100, unique=True)),
                ('occurred_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('A', 'Active'), ('C', 'Closed')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NonConformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('AW', 'Awaiting Action'), ('RN', 'Regulator Notified')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('units', models.CharField(max_length=50)),
                ('limit', models.FloatField()),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('test_method', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FieldSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_at', models.DateTimeField()),
                ('collected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='water_samples_collected', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=255)),
                ('long_description', models.TextField()),
                ('status', models.CharField(choices=[('NF', 'Not Funded'), ('PL', 'Planned'), ('CM', 'Complete')], max_length=2)),
                ('estimated_delivery_date', models.DateField()),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrective_actions', to='dwqmp.incident')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentCorrespondence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='incident_correspondence/')),
                ('date_time', models.DateTimeField()),
                ('comments', models.TextField(blank=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspondences', to='dwqmp.incident')),
            ],
        ),
        migrations.AddField(
            model_name='incident',
            name='non_conformance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='dwqmp.nonconformance'),
        ),
        migrations.CreateModel(
            name='SampleCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='sample_attachments/')),
                ('field_samples', models.ManyToManyField(related_name='collections', to='dwqmp.fieldsample')),
            ],
        ),
        migrations.CreateModel(
            name='SampleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('comments', models.TextField(blank=True)),
                ('field_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='dwqmp.fieldsample')),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dwqmp.testtype')),
            ],
        ),
        migrations.AddField(
            model_name='nonconformance',
            name='sample_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_conformances', to='dwqmp.sampleresult'),
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('spid', models.PositiveIntegerField(unique=True)),
                ('primary_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_water', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DW', 'Drinking Water'), ('WW', 'Waste Water'), ('RW', 'Recycled Water')], max_length=2)),
                ('description', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.TextField()),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='dwqmp.serviceprovider')),
            ],
        ),
        migrations.CreateModel(
            name='TestPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('frequency', models.PositiveIntegerField()),
                ('frequency_units', models.CharField(choices=[('D', 'Days'), ('W', 'Weeks'), ('M', 'Months'), ('Y', 'Years')], max_length=1)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_points', to='dwqmp.scheme')),
                ('test_types', models.ManyToManyField(related_name='test_points', to='dwqmp.testtype')),
            ],
        ),
        migrations.AddField(
            model_name='fieldsample',
            name='test_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='dwqmp.testpoint'),
        ),
    ]
